module.exports = {
  HTTP_METHODS: { DELETE: 'delete', GET: 'get', POST: 'post', PUT: 'put' },
  JSON_SELECTORS: {
    APP: 'config.webServer.app',
    ALLOW_DELETE_MULTIPLE: 'allowDeleteMultiple',
    ASSUME_ID_FIELD_MEANS_UPDATE: 'assumeIdFieldMeansUpdate',
    ENABLE_DB_VERSIONING: 'config.enableDbVersioning',
    FIELDS: 'fields',
    GET_SEL: 'get',
    EXPRESS_IMPLEMENTATION: 'expressImplementation',
    LOGGER: 'logger',
    HTTP_METHOD: 'httpMethod',
    MIDDLEWARES: 'middlewares',
    OFFSET: 'offset',
    OPTIONS_ON_REQUEST: 'mergedRequestParameters',
    PAGE_SIZE: 'pageSize',
    POOL: 'dbConnPool',
    POOL_CONF: 'config.db',
    POOL_END: 'dbConnPool.end',
    POOL_KEY: 'dbConnPool.pgPool',
    POOL_QUERY: 'dbConnPool.query',
    POSTGRES_DB_VERSIONING_CONFIG: 'postgresDbVersioning',
    PUT_SEL: 'put',
    ROUTE: 'route',
    TABLE_NAME: 'tableName',
    TEST_LOGGER: 'config.testLogger',
    WEB_SERVER_START_TIMEOUT: 'config.webServer.startTimeoutMs',
    WEB_SERVER_STOP_TIMEOUT: 'config.webServer.stopTimeoutMs',
    WHERE: 'where',
  },
  MODEL: {
    DEFAULT_PAGE_SIZE: 10,
  },
};
